[input]
base_directory = "posts"
url_prefix = "posts/"
frontmatter_handling = "Omit"

  [[input.files]]
  path = "example-post.mdx"
  url = "example-post"
  title = "Example Post"
  filetype = "Markdown"

  [[input.files]]
  path = "fido-standard.mdx"
  url = "fido-standard"
  title = "Accelerating passwordless authentication"
  filetype = "Markdown"

  [[input.files]]
  path = "hello-world.mdx"
  url = "hello-world"
  title = "Hello World"
  filetype = "Markdown"

  [[input.files]]
  path = "no-blueberries.mdx"
  url = "no-blueberries"
  title = "No Blueberries"
  filetype = "Markdown"
