import fs from "fs"
import matter from "gray-matter"
import Link from "next/link"
import path from "path"
import Layout from "../components/Layout"
import { postFilePaths, POSTS_PATH } from "../utils/mdxUtils"
import readingTime from "reading-time"
import { useEffect } from "react"
import Script from "next/script"

export default function Index ({ posts }) {
  // Initialise Stork
  useEffect(() => {
    stork.register("search", "stork-index.st")
  }, [])

  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by <code>next-mdx-remote</code>.
      </p>
      <div class='stork-wrapper'>
        <input data-stork='search' class='stork-input' />
        <div data-stork='search-output' class='stork-output'></div>
      </div>
      <ul>
        {posts.map(post => (
          <li key={post.filePath}>
            <Link as={`/posts/${post.filePath.replace(/\.mdx?$/, "")}`} href={`/posts/[slug]`}>
              <a>{post.data.title}</a>
            </Link>
            <p>{post.data.readingTime.text}</p>
          </li>
        ))}
      </ul>
      <Script src='https://files.stork-search.net/releases/v1.4.2/stork.js' strategy='beforeInteractive' />
    </Layout>
  )
}

export function getStaticProps () {
  const posts = postFilePaths.map(filePath => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath))
    const { content, data } = matter(source)
    data.readingTime = readingTime(content)

    return {
      content,
      data,
      filePath
    }
  })

  return { props: { posts } }
}
